id: PB95C5402
initial_creation_type: ocr
source_metadata:
  volumes:
    bdb8abe0fc1e42a88ac7a3e81402266f:
      base_file: v079.txt
      image_group_id: I1PD95924
      title: ཆོས་མངོན་པའི་མཛོད་ཀྱི་བཤད་པ།
      total_pages: 1433
      volume_number: 79
